[package]
name = "arboric"
version = "0.1.0"
authors = ["Alistair A. Israel <aisrael@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simplelog = "^0.6.0"
http = "0.1"
hyper = "0.12"
futures = "0.1"
