arboric:
  log:
    console:
      level: info
listeners:
- bind: 0.0.0.0
  port: 4000
  proxy: http://test_api/graphql
  jwt_signing_key:
    from_env:
      key: JWT_SIGNING_KEY
      encoding: hex
  policies:
  - allow:
    - "*"
